---
# Source: prometheus/templates/node-exporter/svc.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    component: "node-exporter"
    app: prometheus
    release: pool-au
    chart: prometheus-15.12.2
    heritage: Helm
  name: pool-au-prometheus-node-exporter
  namespace: noel-test
spec:
  ports:
    - name: metrics
      port: 9100
      protocol: TCP
      targetPort: 9100
  selector:
    component: "node-exporter"
    app: prometheus
    release: pool-au
  type: "ClusterIP"
