apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tls-secret-srenantong-site
  namespace: noel-test
spec:
  backendType: gcpSecretsManager
  template:
    type: kubernetes.io/tls
  data:
    - key: tls-secret-srenantong-site
      name: tls.crt
      property: tls.crt
      isBinary: true
    - key: tls-secret-srenantong-site
      name: tls.key
      property: tls.key
      isBinary: true
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tls-secret-grafana-site
  namespace: noel-test
spec:
  backendType: gcpSecretsManager
  template:
    type: kubernetes.io/tls
  data:
    - key: tls-secret-grafana-site
      name: tls.crt
      property: tls.crt
      isBinary: true
    - key: tls-secret-grafana-site
      name: tls.key
      property: tls.key
      isBinary: true