apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: httpserver
  name: httpserver-service
  namespace: noel-test
spec:
  selector:
    app: httpserver
  ports:
  - protocol: TCP
    name: httpserver
    port: 8080
    targetPort: http-web
  type: NodePort
