---
# Source: prometheus/templates/alertmanager/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: pool-au
    chart: prometheus-15.12.2
    heritage: Helm
  name: pool-au-prometheus-alertmanager
  namespace: noel-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"
