---
# Source: prometheus/templates/alertmanager/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: pool-au
    chart: prometheus-15.12.2
    heritage: Helm
  name: pool-au-prometheus-alertmanager
  namespace: noel-test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9093
  selector:
    component: "alertmanager"
    app: prometheus
    release: pool-au
  sessionAffinity: None
  type: "ClusterIP"
