apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tls-secret-httpserver-site
  namespace: istio-system
spec:
  backendType: gcpSecretsManager
  template:
    type: kubernetes.io/tls
  data:
    - key: tls-secret-httpserver-site
      name: tls.crt
      property: tls.crt
      isBinary: true
    - key: tls-secret-httpserver-site
      name: tls.key
      property: tls.key
      isBinary: true
