---
# Source: grafana/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    helm.sh/chart: grafana-6.38.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: pool-au
    app.kubernetes.io/version: "9.1.5"
    app.kubernetes.io/managed-by: Helm
  name: pool-au-grafana-clusterrole
rules: []
