---
# Source: grafana/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pool-au-grafana-clusterrolebinding
  labels:
    helm.sh/chart: grafana-6.38.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: pool-au
    app.kubernetes.io/version: "9.1.5"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: pool-au-grafana
    namespace: noel-test
roleRef:
  kind: ClusterRole
  name: pool-au-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io
