---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pool-au-grafana
  namespace: noel-test
  labels:
    helm.sh/chart: grafana-6.38.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: pool-au
    app.kubernetes.io/version: "9.1.5"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [pool-au-grafana]
