---
# Source: grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: pool-au-grafana
  namespace: noel-test
  labels:
    helm.sh/chart: grafana-6.38.3
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: pool-au
    app.kubernetes.io/version: "9.1.5"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "b1BBSng0a1UyM3BKMTh5VVJuZFNienk3ZmdEOWltUUZWTG9NajBxMw=="
  ldap-toml: ""
